### ISSUE TITLE
Bug: inconsistency in delete and edit buttons styling.

### ISSUE THREAD

**Issue by Anshgrover23** [Anshgrover23/To-Do-List#1]
### Description
inconsistency in button delete and edit button styling. 

<img width="451" alt="issue" src="https://github.com/user-attachments/assets/f500fe17-e251-432d-91ca-ce9aa848dda9">

**How to reproduce the issue?**
- go to https://anshgrover23.github.io/To-Do-List/
- click add button 
- and make first todo by giving values in both inputs name and date
- secondly make one more todo but with empty inputs see the difference in button styling.

**Comment by Code-Hacker26** [comment]
Hello,
Hope you're doing well.
Could I possibly work on this issue?

Thanks and Regards,
Hani

**Comment by Anshgrover23** [comment]
@Code-Hacker26 i will check your pr and tell you when it will get merge. and thanks for contributing bro.
