### ISSUE TITLE
[BUG] Arrange to-do-list according to date and time

### ISSUE THREAD

**Issue by piyush-gangrade** [Anshgrover23/To-Do-List#40]
Title:
[BUG FIX] Arrange to-do list according to date and time

Description:
This PR addresses the issue where new to-do items are added synchronously, regardless of their specified date and time. The fix ensures that the to-do list arranges items according to their designated date and time, improving organization and user experience.

Add a to-do item with a specific date and time.
Add another to-do item with an earlier date or time.
Verify that the items are displayed in the correct order according to their respective dates and times.
Expected behavior:
The to-do list should now correctly arrange items according to their date and time, ensuring that users see their tasks in chronological order.

![Screenshot 2024-10-12 010718](https://github.com/user-attachments/assets/4762a211-3084-40f0-97e5-ae3b4bb76332)

Please assign this to me.

**Comment by somewherelostt** [comment]
Hello, I have reviewed the contributing.md file, as well as the index.html, CSS, and JavaScript files. I am interested in working on this issue. Could you please assign it to me? Also, if it is part of Hacktoberfest, please mark it as [hacktoberfest]."s [hacktoberfest].
